// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Uuid = require("uuid");
var Belt_Int = require("rescript/lib/js/belt_Int.js");
var Clarification = require("./Clarification.bs.js");

function MakePrimaryKeyUuid(ColumnName) {
  var $$new = function (param) {
    return Uuid.v4();
  };
  var stringify = function (pk) {
    return pk;
  };
  var parse = function (str) {
    if (Uuid.validate(str)) {
      return str;
    }
    
  };
  var applyClarification = function (knex, clar) {
    return Clarification.applyStringClarification(knex, ColumnName.columnName, clar);
  };
  return {
          $$new: $$new,
          stringify: stringify,
          parse: parse,
          applyClarification: applyClarification
        };
}

function MakePrimaryKeyAutoIncrementInt(ColumnName) {
  var $$new = function (param) {
    
  };
  var stringify = function (pk) {
    return String(pk);
  };
  var parse = Belt_Int.fromString;
  var applyClarification = function (knex, clar) {
    return Clarification.applyIntClarification(knex, ColumnName.columnName, clar);
  };
  return {
          $$new: $$new,
          stringify: stringify,
          parse: parse,
          applyClarification: applyClarification
        };
}

exports.MakePrimaryKeyUuid = MakePrimaryKeyUuid;
exports.MakePrimaryKeyAutoIncrementInt = MakePrimaryKeyAutoIncrementInt;
/* uuid Not a pure module */
