// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var scalarifyDefault = (function (a) {
  return a;
});

var stringifyVal = (function (i) {
    return i.toString();
  });

var IntValueTrait = {
  scalarify: scalarifyDefault,
  stringifyVal: stringifyVal
};

var buildColumn = (function (table, colName) {
      return table.integer(colName);
    });

var IntValueType = {
  scalarify: scalarifyDefault,
  stringifyVal: stringifyVal,
  buildColumn: buildColumn
};

var buildColumn$1 = (function (table, colName) {
      return table.tinyInt(colName);
    });

var TinyIntValueType = {
  scalarify: scalarifyDefault,
  stringifyVal: stringifyVal,
  buildColumn: buildColumn$1
};

var buildColumn$2 = (function (table, colName) {
      return table.smallInt(colName);
    });

var SmallIntValueType = {
  scalarify: scalarifyDefault,
  stringifyVal: stringifyVal,
  buildColumn: buildColumn$2
};

var buildColumn$3 = (function (table, colName) {
      return table.mediumInt(colName);
    });

var MediumIntIntValueType = {
  scalarify: scalarifyDefault,
  stringifyVal: stringifyVal,
  buildColumn: buildColumn$3
};

var buildColumn$4 = (function (table, colName) {
      return table.bigInt(colName);
    });

var BigIntValueType = {
  scalarify: scalarifyDefault,
  stringifyVal: stringifyVal,
  buildColumn: buildColumn$4
};

var stringifyVal$1 = (function (i) {
    return i.toString();
  });

var FloatValueTrait = {
  scalarify: scalarifyDefault,
  stringifyVal: stringifyVal$1
};

var buildColumn$5 = (function (table, colName) {
      return table.float(colName);
    });

var FloatValueType = {
  scalarify: scalarifyDefault,
  stringifyVal: stringifyVal$1,
  buildColumn: buildColumn$5
};

var buildColumn$6 = (function (table, colName) {
      return table.double(colName);
    });

var DoubleValueType = {
  scalarify: scalarifyDefault,
  stringifyVal: stringifyVal$1,
  buildColumn: buildColumn$6
};

var stringifyVal$2 = (function (i) {
    return i;
  });

var StringValueTrait = {
  scalarify: scalarifyDefault,
  stringifyVal: stringifyVal$2
};

var buildColumn$7 = (function (table, colName) {
      return table.string(colName);
    });

var StringValueType = {
  scalarify: scalarifyDefault,
  stringifyVal: stringifyVal$2,
  buildColumn: buildColumn$7
};

exports.scalarifyDefault = scalarifyDefault;
exports.IntValueTrait = IntValueTrait;
exports.IntValueType = IntValueType;
exports.TinyIntValueType = TinyIntValueType;
exports.SmallIntValueType = SmallIntValueType;
exports.MediumIntIntValueType = MediumIntIntValueType;
exports.BigIntValueType = BigIntValueType;
exports.FloatValueTrait = FloatValueTrait;
exports.FloatValueType = FloatValueType;
exports.DoubleValueType = DoubleValueType;
exports.StringValueTrait = StringValueTrait;
exports.StringValueType = StringValueType;
/* No side effect */
